# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af88bcc85003504500c7a4c76ec769549ff286f10f5adb2e69bff50b88623c1702f2c67f59062d22a3e845f021f1b9645a04c5f42f4984af0ebb28b736c560f1

test:
  secret_key_base: 80b1742fcd366992661840b80aace44c0fc7f466df517942f103f3a2e28753755cdfe8bad5f229ad124e404cacc321d66cdb8a71db802e97ee58818ca97cb3b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
